"""empty message

Revision ID: 16a1a97af657
Revises: 
Create Date: 2020-03-01 16:00:20.514614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a1a97af657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('color', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'themes', ['assignment_id', 'color'])
    op.create_unique_constraint(None, 'themes', ['themeName'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='unique')
    op.drop_constraint(None, 'themes', type_='unique')
    op.drop_column('themes', 'color')
    # ### end Alembic commands ###
